export const  claves = {
    "-Neip2TkzqqFIRdrl4_E": {
      "concepto": "zcsxdvxcv",
      "facturaRemision": "factura",
      "fecha_recibido": "Tue Sep 19 2023 13:04:27 GMT-0600 (hora estándar central)",
      "id_os": "-NeilMdGut9oYmtS4Of5",
      "metodo": "1",
      "monto": 1200,
      "referencia": "xcvxcv",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-Neipdx0pQwe9IolbZNi": {
      "concepto": "xcvxcvxc",
      "facturaRemision": "nota",
      "fecha_recibido": "Tue Sep 19 2023 13:07:04 GMT-0600 (hora estándar central)",
      "id_os": "-NeilMdGut9oYmtS4Of5",
      "metodo": "2",
      "monto": 1200,
      "referencia": "xcvxcv",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-NeiurV8ISOX_FdQBCO5": {
      "concepto": "sadsa",
      "facturaRemision": "nota",
      "fecha_recibido": "Tue Sep 19 2023 13:29:51 GMT-0600 (hora estándar central)",
      "id_os": "-NeiehcXToEW7W0O4fUd",
      "metodo": "1",
      "monto": 1500,
      "referencia": "asdasd",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-Neiws4FO7nSm4hDaUcy": {
      "concepto": "gfhfgh",
      "facturaRemision": "nota",
      "fecha_recibido": "Tue Sep 19 2023 13:38:37 GMT-0600 (hora estándar central)",
      "id_os": "-NeiehcXToEW7W0O4fUd",
      "metodo": "2",
      "monto": 100,
      "referencia": "fghfgh",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-Neix0qVitSdlPvqtubV": {
      "concepto": "sdfsd",
      "facturaRemision": "factura",
      "fecha_recibido": "Tue Sep 19 2023 13:39:17 GMT-0600 (hora estándar central)",
      "id_os": "-NeiehcXToEW7W0O4fUd",
      "metodo": "1",
      "monto": 55,
      "referencia": "dsfsdf",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-Neixpcf6jMJVuu0fD_x": {
      "concepto": "sdfdsfsd",
      "facturaRemision": "nota",
      "fecha_recibido": "Tue Sep 19 2023 13:42:49 GMT-0600 (hora estándar central)",
      "id_os": "-NeiehcXToEW7W0O4fUd",
      "metodo": "2",
      "monto": 444,
      "referencia": "dsfsdfsd",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-NeixumLUo0B6QErOA1p": {
      "concepto": "asdsadas",
      "facturaRemision": "factura",
      "fecha_recibido": "Tue Sep 19 2023 13:43:10 GMT-0600 (hora estándar central)",
      "id_os": "-NeilHGTHBi2jAL9DX78",
      "metodo": "2",
      "monto": 232,
      "referencia": "aaaaaa",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-NejjoyX5qDca6WR8x4Q": {
      "concepto": "cvbcv",
      "facturaRemision": "nota",
      "fecha_recibido": "Tue Sep 19 2023 17:21:14 GMT-0600 (hora estándar central)",
      "id_os": "-NeiehcXToEW7W0O4fUd",
      "metodo": "1",
      "monto": 500,
      "referencia": "cvbbbbbbb",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-NejoGAiZyRN2uR6TnYh": {
      "concepto": "dfgdfdddd",
      "facturaRemision": "nota",
      "fecha_recibido": "Mon Sep 18 2023 17:40:29 GMT-0600 (hora estándar central)",
      "id_os": "-NeiehcXToEW7W0O4fUd",
      "metodo": "1",
      "monto": 600,
      "referencia": "mmmm",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-Nejr92qnEs4rkFT4OH9": {
      "concepto": "sdssssss",
      "facturaRemision": "factura",
      "fecha_recibido": "Mon Sep 18 2023 17:53:15 GMT-0600 (hora estándar central)",
      "id_os": "-NeiehcXToEW7W0O4fUd",
      "metodo": "3",
      "monto": 1400,
      "referencia": "mmmmmfffffff",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-NeoK5c_vs0CpA797Sx0": {
      "concepto": "xcvxcvx",
      "facturaRemision": "factura",
      "fecha_recibido": "Wed Sep 20 2023 14:42:29 GMT-0600 (hora estándar central)",
      "id_os": "-NeoEUfB8p0Wpac9JDFd",
      "metodo": "2",
      "monto": 1200,
      "referencia": "xcvxcv",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-NeoK8kDeFCw3jbXmQ0B": {
      "concepto": "zxczxc",
      "facturaRemision": "nota",
      "fecha_recibido": "Wed Sep 20 2023 14:42:48 GMT-0600 (hora estándar central)",
      "id_os": "-NeoEUfB8p0Wpac9JDFd",
      "metodo": "2",
      "monto": 500,
      "referencia": "zxczxczxc",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-Neomzdh435eoiivJPy6": {
      "concepto": "dfgdfgdf",
      "facturaRemision": "factura",
      "fecha_recibido": "Wed Sep 20 2023 16:53:10 GMT-0600 (hora estándar central)",
      "id_os": "-NeoEUfB8p0Wpac9JDFd",
      "metodo": "2",
      "monto": 800,
      "referencia": "dfgdfgd",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-Neon4fAGTeHVrEkjolh": {
      "concepto": "fdgdfg",
      "facturaRemision": "factura",
      "fecha_recibido": "Wed Sep 20 2023 16:53:35 GMT-0600 (hora estándar central)",
      "id_os": "-NeoEUfB8p0Wpac9JDFd",
      "metodo": "3",
      "monto": 5000,
      "referencia": "dfgdf",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-Neon9orejN0d3Uk0Lnd": {
      "concepto": "xcvxcvx",
      "facturaRemision": "factura",
      "fecha_recibido": "Wed Sep 20 2023 16:53:54 GMT-0600 (hora estándar central)",
      "id_os": "-NeoEUfB8p0Wpac9JDFd",
      "metodo": "2",
      "monto": 1400,
      "referencia": "xcvxcv",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-NeonDcF_zb71TswBbt6": {
      "concepto": "xcvxcv",
      "facturaRemision": "factura",
      "fecha_recibido": "Wed Sep 20 2023 16:54:12 GMT-0600 (hora estándar central)",
      "id_os": "-NeoEUfB8p0Wpac9JDFd",
      "metodo": "2",
      "monto": 5000,
      "referencia": "xcvxcv",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-NflaBnJU0Bzi5r2Myo_": {
      "concepto": "sdfffgdsg",
      "facturaRemision": "factura",
      "fecha_recibido": "Mon Oct 02 2023 12:14:01 GMT-0600 (hora estándar central)",
      "id_os": "-NeoEUfB8p0Wpac9JDFd",
      "metodo": "1",
      "monto": 144,
      "referencia": "dfgdfg",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-Nfld_xALnjF07U0OD1U": {
      "concepto": "sdfsdf",
      "facturaRemision": "factura",
      "fecha_recibido": "Mon Oct 02 2023 12:28:50 GMT-0600 (hora estándar central)",
      "id_os": "-NfD6JIW2RFnsunu83r4",
      "metodo": "1",
      "monto": 333,
      "referencia": "sdfsdf",
      "status": true,
      "sucursal": "-N2glF34lV3Gj0bQyEWK",
      "tipo": "orden"
    },
    "-NfldgRRuza8rdWdk1dZ": {
      "concepto": "zsxcvxcv",
      "facturaRemision": "factura",
      "fecha_recibido": "Mon Oct 02 2023 12:29:16 GMT-0600 (hora estándar central)",
      "id_os": "-NeoEUfB8p0Wpac9JDFd",
      "metodo": "1",
      "monto": 345,
      "referencia": "xcvxcvx",
      "status": true,
      "sucursal": "-N2gkzuYrS4XDFgYciId",
      "tipo": "orden"
    },
    "-Nflh0Sp9YycwSVPpv6N": {
      "concepto": "sadasfsd",
      "facturaRemision": "factura",
      "fecha_recibido": "Mon Oct 02 2023 12:43:49 GMT-0600 (hora estándar central)",
      "id_os": "-NfD6JIW2RFnsunu83r4",
      "metodo": "1",
      "monto": 500,
      "referencia": "sdfsdf",
      "status": true,
      "sucursal": "-N2glF34lV3Gj0bQyEWK",
      "tipo": "orden"
    },
    "-Nflu7C8QMBNNxjT6kLJ": {
      "concepto": "jvvgkk",
      "facturaRemision": "nota",
      "fecha_recibido": "Mon Oct 02 2023 13:41:04 GMT-0600 (hora estándar central)",
      "id_os": "-NfD6JIW2RFnsunu83r4",
      "metodo": "1",
      "monto": 666,
      "referencia": "hvhmhhh",
      "status": true,
      "sucursal": "-N2glF34lV3Gj0bQyEWK",
      "tipo": "orden"
    },
    "-NflwnJb6lyNKKQz1o3X": {
      "concepto": "tdthfhg",
      "facturaRemision": "factura",
      "fecha_recibido": "Mon Oct 02 2023 13:52:42 GMT-0600 (hora estándar central)",
      "id_os": "-NfD6JIW2RFnsunu83r4",
      "metodo": "1",
      "monto": 44,
      "referencia": "fhjgjf",
      "status": true,
      "sucursal": "-N2glF34lV3Gj0bQyEWK",
      "tipo": "orden"
    }
  }